import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform } from "esbuild";
import { renderPortalClientScript } from "../src/views/portal.js";

const currentFilePath = fileURLToPath(import.meta.url);
const scriptsDirectory = path.dirname(currentFilePath);
const projectRoot = path.resolve(scriptsDirectory, "..");
const outputPath = path.join(projectRoot, "src/generated/portalClient.generated.ts");

const buildPortalClient = async () => {
  const rawScript = renderPortalClientScript();
  const transformed = await transform(rawScript, {
    loader: "js",
    target: "es2015",
    format: "iife",
    charset: "utf8",
    minify: false,
    legalComments: "none",
  });

  const output = `// Generated by scripts/buildPortalClient.ts
// Do not edit this file directly.

export const portalClientScript = ${JSON.stringify(transformed.code)};
`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
};

buildPortalClient().catch((error) => {
  console.error("Failed to build portal client asset", error);
  process.exit(1);
});
